/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package adminRole.view;

import java.awt.Color;

/**
 *
 * @author GIAHUY
 */
public class AddPatientForm extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public AddPatientForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        saveButton.setBackground(Color.WHITE);
        cancelButton.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(757, 588));
        setMinimumSize(new java.awt.Dimension(757, 588));
        setPreferredSize(new java.awt.Dimension(757, 588));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 370, 480, 108);

        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(cancelButton);
        cancelButton.setBounds(560, 510, 70, 20);

        saveButton.setText("Save");
        saveButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(saveButton);
        saveButton.setBounds(650, 510, 70, 20);

        jTextField11.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField11);
        jTextField11.setBounds(550, 300, 64, 30);

        jTextField10.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField10);
        jTextField10.setBounds(370, 300, 64, 30);

        jTextField9.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField9);
        jTextField9.setBounds(370, 230, 64, 30);

        jTextField7.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(550, 230, 64, 30);

        jTextField8.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 300, 64, 30);

        jTextField6.setMaximumSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 230, 64, 30);

        jLabel5.setText("Insurance Expiration:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 310, 124, 16);

        jLabel6.setText("Underlying Disease");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 380, 113, 16);

        jLabel4.setText("Birthday:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 240, 80, 16);

        jLabel3.setText("Adress");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 60, 16);

        jLabel2.setText("Phone:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 110, 16);

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 110, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 30, 348, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 100, 348, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 160, 515, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPatientForm dialog = new AddPatientForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
