/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adminRole.view;

import adminRole.controller.PatientPageController;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author GIAHUY
 */
public class PatientPage extends javax.swing.JPanel {

    /**
     * Creates new form PatientPane
     */
    private PatientPageController controller;
    public void addNewTab(JPanel tab)
    {
        this.tabbedPane.add(tab, tab.toString());
        this.tabbedPane.setSelectedIndex((tabbedPane.getTabCount()- 1));
    }
    
    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }
    
    public PatientPage() {
        initComponents();
        controller = new PatientPageController(this);
        
        addNewTab(new PatientListTab(this));
        tabbedPane.addChangeListener(e -> {
            ((Tab)tabbedPane.getSelectedComponent()).refreshData();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(false);
        setFocusCycleRoot(true);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1536, 793));
        setMinimumSize(new java.awt.Dimension(1536, 793));
        setPreferredSize(new java.awt.Dimension(1536, 793));
        setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 793));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 793);

        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        add(tabbedPane);
        tabbedPane.setBounds(300, 0, 1230, 790);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
