/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctorRole.view;
import adminRole.view.*;
import Login.LoginView;
import Model.UserModel;
import adminRole.controller.MainViewController;
import doctorRole.controller.DoctorMainViewController;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import javax.swing.UIManager.LookAndFeelInfo;
/**
 *
 * @author GIAHUY
 */
public class DoctorMainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    //components of frame
    private JPanel[] paneList;
    private DoctorMainViewController controller;
    private UserModel user;

    public UserModel getUser() {
        return user;
    }

    public void setUser(UserModel user) {
        this.user = user;
    }
           
    
    public DoctorMainView(UserModel user) {
        initComponents();
        this.user = user;
        //set listener for event
        patientSwitchPaneButton.addActionListener(e -> switchPane(0)); 
        scheduleSwitchPaneButton.addActionListener(e -> switchPane(1));
        medicineSwitchPaneButton.addActionListener(e -> switchPane(2));
        logoutButton.addActionListener(e -> {
            controller.logout();
        });
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                int choice = JOptionPane.showConfirmDialog(DoctorMainView.this, "Do you want to close the program?", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (choice == JOptionPane.OK_OPTION)
                    DoctorMainView.this.dispose();
            }         
        });
        
        
        //set properties for components
        this.setTitle("Clinic Management(Doctor)");
        this.setLocationRelativeTo(null);
        this.setSize(1550, 830); 
        this.setResizable(false);
        this.setIconImage(new ImageIcon("C:\\Users\\GIAHUY\\Pictures\\Screenshots\\logo.png").getImage());
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.controller = new DoctorMainViewController(this); // controller
        this.paneList = new JPanel[3]; 
        paneList[0] = new PatientPage(user); //patient
        paneList[1] =  new SchedulePage(user);
        paneList[2] =  new MedicinePage(user);
 
        
        patientSwitchPaneButton.setBackground(Color.WHITE);
        scheduleSwitchPaneButton.setBackground(Color.WHITE);
        medicineSwitchPaneButton.setBackground(Color.WHITE);     
        logoutButton.setBackground(Color.WHITE);
        this.switchPane(0);
        
    }
    private void switchPane(int index)
    {
        contentPane.removeAll();
        contentPane.add(this.paneList[index]);
        contentPane.revalidate();
        contentPane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientSwitchPaneButton = new javax.swing.JButton();
        scheduleSwitchPaneButton = new javax.swing.JButton();
        medicineSwitchPaneButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        contentPane = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1100, 620));
        setSize(new java.awt.Dimension(1100, 620));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        patientSwitchPaneButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        patientSwitchPaneButton.setForeground(new java.awt.Color(153, 204, 255));
        patientSwitchPaneButton.setText("Patient");
        patientSwitchPaneButton.setToolTipText("");
        patientSwitchPaneButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        patientSwitchPaneButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        patientSwitchPaneButton.setMaximumSize(new java.awt.Dimension(50, 50));
        patientSwitchPaneButton.setMinimumSize(new java.awt.Dimension(50, 50));
        patientSwitchPaneButton.setName(""); // NOI18N
        patientSwitchPaneButton.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel1.add(patientSwitchPaneButton);
        patientSwitchPaneButton.setBounds(0, 0, 80, 50);

        scheduleSwitchPaneButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        scheduleSwitchPaneButton.setForeground(new java.awt.Color(153, 204, 255));
        scheduleSwitchPaneButton.setText("Schedule");
        scheduleSwitchPaneButton.setToolTipText("");
        scheduleSwitchPaneButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        scheduleSwitchPaneButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        scheduleSwitchPaneButton.setMaximumSize(new java.awt.Dimension(80, 80));
        scheduleSwitchPaneButton.setMinimumSize(new java.awt.Dimension(80, 80));
        scheduleSwitchPaneButton.setPreferredSize(new java.awt.Dimension(80, 80));
        scheduleSwitchPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleSwitchPaneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(scheduleSwitchPaneButton);
        scheduleSwitchPaneButton.setBounds(80, 0, 80, 50);

        medicineSwitchPaneButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        medicineSwitchPaneButton.setForeground(new java.awt.Color(153, 204, 255));
        medicineSwitchPaneButton.setText("Medicine");
        medicineSwitchPaneButton.setToolTipText("");
        medicineSwitchPaneButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        medicineSwitchPaneButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        medicineSwitchPaneButton.setMaximumSize(new java.awt.Dimension(80, 80));
        medicineSwitchPaneButton.setMinimumSize(new java.awt.Dimension(80, 80));
        medicineSwitchPaneButton.setPreferredSize(new java.awt.Dimension(80, 80));
        medicineSwitchPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineSwitchPaneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(medicineSwitchPaneButton);
        medicineSwitchPaneButton.setBounds(160, 0, 80, 50);

        logoutButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 51, 51));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(logoutButton);
        logoutButton.setBounds(1410, 10, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 50);

        contentPane.setMaximumSize(new java.awt.Dimension(1550, 750));
        contentPane.setMinimumSize(new java.awt.Dimension(1550, 750));
        contentPane.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1550, 760));
        jPanel2.setMinimumSize(new java.awt.Dimension(1550, 760));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        contentPane.add(jPanel2, "card2");

        getContentPane().add(contentPane);
        contentPane.setBounds(0, 50, 1550, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleSwitchPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleSwitchPaneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleSwitchPaneButtonActionPerformed

    private void medicineSwitchPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineSwitchPaneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineSwitchPaneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane contentPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton medicineSwitchPaneButton;
    private javax.swing.JButton patientSwitchPaneButton;
    private javax.swing.JButton scheduleSwitchPaneButton;
    // End of variables declaration//GEN-END:variables
}
